# Generated by Django 4.1.4 on 2022-12-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0003_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=250)),
                ("password", models.IntegerField()),
                ("password1", models.IntegerField()),
            ],
        ),
    ]
