# Generated by Django 4.1.4 on 2022-12-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0004_register"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login", name="password", field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="login", name="username", field=models.CharField(max_length=64),
        ),
    ]
