# Generated by Django 4.1.4 on 2022-12-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0006_form"),
    ]

    operations = [
        migrations.DeleteModel(name="form",),
    ]
