# Generated by Django 4.1.4 on 2022-12-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0007_delete_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="img",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="pics")),
            ],
        ),
    ]
